# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-26 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesdata',
            name='start_date',
            field=models.DateField(max_length=100),
        ),
        migrations.AlterField(
            model_name='coursesdata',
            name='start_time',
            field=models.TimeField(max_length=100),
        ),
    ]
